name: Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Debug : vérifie les chemins réels du repo
      - name: List files
        run: |
          pwd
          ls -la
          ls -la web || true
          ls -la web/app || true

      - name: Setup Node (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Installe les deps du front
      - name: Install deps
        working-directory: web/app
        run: npm install

      # Build Vite avec secrets injectés directement dans l'env de l'étape
      - name: Build (Vite + env injection)
        working-directory: web/app
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
          echo "[ENV] URL set? $([[ -n \"$VITE_SUPABASE_URL\" ]] && echo yes || echo no)"
          echo "[ENV] ANON set? $([[ -n \"$VITE_SUPABASE_ANON_KEY\" ]] && echo yes || echo no)"
          npm run build
          echo "[DIST]"
          ls -la dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/app/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
