name: Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Debug: on vérifie l'arborescence réelle du repo
      - name: List files
        run: |
          pwd
          ls -la
          ls -la web || true
          ls -la web/app || true

      - name: Setup Node (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Écrit les variables Vite dans web/app/.env
      - name: Write env (Vite)
        working-directory: web/app
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
          echo "[.env created in web/app/]"

      - name: Install deps (no lockfile required)
        working-directory: web/app
        run: npm install

      - name: Build
        working-directory: web/app
        run: npm run build

      # Si tu déploies sur GitHub Pages :
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/app/dist

  deploy:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
