name: Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}   # permet de le lancer à la main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # → ICI tu exécutes du bash grâce à "run: |"
      - name: Write env (Vite)
        working-directory: web/app
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
          echo "[.env created in web/app/]"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/app/package-lock.json

      - name: Install deps (bash)
        working-directory: web/app
        run: |
          npm ci
          npm -v
          node -v

      - name: Build (bash)
        working-directory: web/app
        run: |
          npm run build
          ls -la dist

      # (Optionnel) Déploiement GitHub Pages
      - name: Upload artifact
        if: success()
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/app/dist

  deploy:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
